services:
  - type: web
    name: spotify-track-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false  # You'll need to add this in Render's dashboard
      - key: SPOTIFY_CLIENT_SECRET
        sync: false  # You'll need to add this in Render's dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
